AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 
  This CloudFormation template will deploy an instance of the SSOSync-Staging
  candidate releases (via privately shared app in the AWS Serverless Application
  Repository (SAR) within the Staging Account.

Parameters:
  ApplicationArn:
    Description: The candidate release in the SAR
    Default: 'arn:aws:serverlessrepo:<AWS::Region>:<AccountId>:applications/<ApplicationName>'
    Type: String
  SemanticVersion:
    Description: The version of the candidate release in the SAR
    Default: 'v0.0.0-Staging'
    Type: String
 
Resources:
  SARApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: '${ApplicationArn}'
        SemanticVersion: "${SemanticVersion}"
      Parameters:
        GoogleAdminEmail: '{{resolve:secretsmanager:TestGoogleAdminEmail}}'
        GoogleCredentials: '{{resolve:secretsmanager:TestGoogleCredentials}}'
        SCIMEndpointUrl: '{{resolve:secretsmanager:TestSCIMEndpointUrl}}'
        SCIMEndpointAccessToken: '{{resolve:secretsmanager:TestSCIMAccessToken}}'
        SyncMethod: groups
        GoogleUserMatch: 'name:*'
        GoogleGroupMatch: 'name:AWS*'
        LogLevel: warn
        LogFormat: json
        IgnoreUsers: None
        IgnoreGroups: None
        IncludeGroups: None
        ScheduleExpression: 'rate(1 day)'

  FunctionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SSOSyncArn
      Type: String
      Value: !GetAtt SARApp.Outputs.FunctionArn
      Description: The Arn of the lambda function ssosync
 
Outputs:
  FunctionArn:
    Description: "The Arn of the deployed lambda function"
    Value: !GetAtt SARApp.Outputs.FunctionArn
    Export:
      Name: FunctionArn
